### PR TITLE
Add Chevy's season 15 pve loot list.

### PR DESCRIPTION
**Pull request by Deanosim**
I used [wishlists.littlelight.club](https://wishlists.littlelight.club) to make this from the list Chevy created, which can be seen [here](https://media.discordapp.net/attachments/767567903083331594/880937722733277234/image0.png)

### CODE REVIEW

**Comment by 48klocs** [comment]
Oh heck yeah - I'll have to give this a look over, but it could be just the danged ticket.

**Review by bivalent — APPROVED** [review]
LGTM. 

I created a script that reviewers can use that converts to LittleLight format from the DIM text file, so that it can be uploaded to LL. Useful to visualize the rolls.

https://github.com/bivalent/DIM-to-LL-converter

Feel free to use it, or use your own tools to validate

**Comment by Deanosim** [comment]
Oh interesting, It's been a long time since I've used LL, I normally just use DIM, I noticed in the little light wishlist maker you can export in a number of other formats including DIM format. I'll have to see what it looks like in Little Light, as currently in D2 I don't have any of the rolls for the guns in the list to see if it's working correctly, I just kinda assumed it was because it looks like it's formatted the same as previous lists I've seen, and other lists I've worked on that worked fine in the past.

**Comment by Deanosim** [comment]
So I've seen a couple of reports of not seeing and season of the lost weapons with thumbs up in DIM, and I haven't seem any either, I'm unsure if it's just bad RNG/luck or theirs something wrong with the wishlist.

**Comment by 48klocs** [comment]
Eh, I pretty consistently see complaints about the wishlist "not working" early in the season.

Until I get a specific "I have this particular exact matching roll and it's not showing up" report, I don't spend time digging in. I ran `npm cleanrolls` and it didn't complain about this list, so who knows.

**Comment by mattsigal** [comment]
If it is any help, I just used "season:current is:wishlist" and it flagged two items (a Canis Major and a Chrysura Melo), so the rolls have been loaded but yeah. With only Chevy's recommendations included, I guess there are still a lot of "holes".

**Comment by Deanosim** [comment]
Ah that's very good then!
I was talking to someone in my clan before and we realised that the Fractethyst shotgun isn't even in Chevy's list so yeah I think you're correct and theirs a lot of holes. worked on converting one of the pinned lists on r/sharditkeep it earlier and that fills in some of the gaps, but that list is missing all the selections for perk slot 1 and 2 so it's not perfect.

**Pull request merged**
